//! Lock-free intrusive stacks and their epoch reclamation contracts.
use crate::{CLOSED_TAG, PopError, PushError, current_thread_id};
use crossbeam_epoch::{self as epoch, Atomic, Shared};
use crossbeam_utils::CachePadded;
use intrusive_collections::singly_linked_list::{AtomicLinkOps, SinglyLinkedListOps};
use intrusive_collections::{Adapter, LinkOps, PointerOps, SinglyLinkedListAtomicLink};
use std::ptr::NonNull;
use std::sync::atomic::Ordering;

type Pointer<A> = <<A as Adapter>::PointerOps as PointerOps>::Pointer;
type Link<A> = <<A as Adapter>::LinkOps as ConcurrentLinkOps>::Link;

/// Link operations usable by concurrent Treiber-stack readers.
///
/// # Safety
/// All methods must be thread-safe and must not panic. `try_acquire` must
/// exclusively claim an unlinked link across *all* compatible collections,
/// synchronizing with its previous release. `release` relinquishes that claim.
/// `load_next` and `store_next` must access the same atomic next pointer without
/// creating exclusive references to the node. A relaxed access is sufficient:
/// the stack publishes initialization through a release head CAS and reads it
/// through an acquire head load. Operations must preserve pointer provenance.
/// `Link` must have alignment >= 2, and its address must stay fixed while owned.
/// For lock-free progress, implementations must not block or acquire locks.
///
/// These operations use `&self`; upstream `&mut self` methods alone do not
/// provide a concurrency contract. Only the singly-linked atomic implementation
/// is provided here; similarly named links for other collections may differ.
pub unsafe trait ConcurrentLinkOps:
    LinkOps<LinkPtr = NonNull<Self::Link>> + Send + Sync
{
    /// The embedded link, not the enclosing value.
    type Link: Send + Sync + 'static;
    /// Claims a live link not already owned by any collection.
    /// # Safety
    /// `link` must remain valid for the call.
    unsafe fn try_acquire(&self, link: NonNull<Self::Link>) -> bool;
    /// Releases a claimed link after all old readers have finished.
    /// # Safety
    /// Caller owns the claim and no reader may still access the old next pointer.
    unsafe fn release(&self, link: NonNull<Self::Link>);
    /// Reads a claimed link's next pointer.
    /// # Safety
    /// Caller must protect the link's lifetime, e.g. with an epoch guard.
    unsafe fn load_next(&self, link: NonNull<Self::Link>) -> Option<NonNull<Self::Link>>;
    /// Updates a claimed, unpublished link.
    /// # Safety
    /// No reader may access this link until the write has been published.
    unsafe fn store_next(&self, link: NonNull<Self::Link>, next: Option<NonNull<Self::Link>>);
}

// SAFETY: this specific upstream link stores next atomically, including the
// unlinked marker. Its operations object is stateless, so a local copy supplies
// the upstream &mut receiver without aliasing an operations object.
unsafe impl ConcurrentLinkOps for AtomicLinkOps {
    type Link = SinglyLinkedListAtomicLink;
    unsafe fn try_acquire(&self, link: NonNull<Self::Link>) -> bool {
        let mut ops = *self;
        unsafe { LinkOps::acquire_link(&mut ops, link) }
    }
    unsafe fn release(&self, link: NonNull<Self::Link>) {
        let mut ops = *self;
        unsafe { LinkOps::release_link(&mut ops, link) }
    }
    unsafe fn load_next(&self, link: NonNull<Self::Link>) -> Option<NonNull<Self::Link>> {
        unsafe { SinglyLinkedListOps::next(self, link) }
    }
    unsafe fn store_next(&self, link: NonNull<Self::Link>, next: Option<NonNull<Self::Link>>) {
        let mut ops = *self;
        unsafe { SinglyLinkedListOps::set_next(&mut ops, link, next) }
    }
}

/// An adapter whose raw ownership can outlive a stack and cross epoch callbacks.
///
/// # Safety
/// Clones must refer to the same link in each value and have interchangeable
/// pointer operations: a pointer erased by one clone can be restored by any
/// other clone. Cloning and all adapter/pointer operations must not panic.
/// Conversions must not create exclusive references to values or their links
/// while the collection owns them. `into_raw` must preserve the allocation and
/// its address until the matching `from_raw`, even after the stack is dropped.
/// Outstanding shared owners must not move/free the node, mutate its link, or
/// access payload through exclusive references during that interval. Ordinary
/// `Box<T>` and `Arc<T>` adapters generated by `intrusive_adapter!` satisfy these
/// requirements when their link type satisfies `ConcurrentLinkOps`.
///
/// The stack separately requires `Pointer: Send + 'static`. Borrowed scoped
/// nodes cannot generally be retired into a global epoch collector.
/// Implementations must not block if lock-free core progress is required.
///
/// Adapters do not opt in implicitly:
/// ```compile_fail
/// use concurrent_sharded_stack::{IntrusiveShardedStack, intrusive_collections};
/// use intrusive_collections::{intrusive_adapter, SinglyLinkedListAtomicLink};
/// struct Node { link: SinglyLinkedListAtomicLink }
/// intrusive_adapter!(A = Box<Node>: Node { link => SinglyLinkedListAtomicLink });
/// let stack = IntrusiveShardedStack::new(A::new()); // Missing EpochAdapter.
/// ```
/// Non-atomic links are rejected even when the adapter opts in:
/// ```compile_fail
/// use concurrent_sharded_stack::{EpochAdapter, IntrusiveShardedStack, intrusive_collections};
/// use intrusive_collections::{intrusive_adapter, SinglyLinkedListLink};
/// struct Node { link: SinglyLinkedListLink }
/// intrusive_adapter!(A = Box<Node>: Node { link => SinglyLinkedListLink });
/// unsafe impl EpochAdapter for A {}
/// let stack = IntrusiveShardedStack::new(A::new()); // Missing ConcurrentLinkOps.
/// ```
pub unsafe trait EpochAdapter: Adapter + Clone + Send + Sync + 'static {}

/// A removed node whose link is still reserved until its epoch grace period.
///
/// This token provides no access to the value or link. Call [`defer`](Self::defer)
/// to receive the original pointer after old readers finish. Dropping the token
/// schedules destruction instead. Forgetting it leaks the node, like forgetting
/// an owning pointer. This token is not a pinned epoch guard.
pub struct Retired<A: EpochAdapter>
where
    A::LinkOps: ConcurrentLinkOps,
    Pointer<A>: Send + 'static,
{
    link: Option<NonNull<Link<A>>>,
    adapter: A,
}

// SAFETY: the token owns the erased Pointer (which is Send); it never exposes
// the value while epoch readers may exist. Adapter clones can restore it.
unsafe impl<A: EpochAdapter> Send for Retired<A>
where
    A::LinkOps: ConcurrentLinkOps,
    Pointer<A>: Send + 'static,
{
}

impl<A: EpochAdapter> Retired<A>
where
    A::LinkOps: ConcurrentLinkOps,
    Pointer<A>: Send + 'static,
{
    /// Schedules delivery on a collecting thread after the grace period.
    ///
    /// The callback may free or reinsert the returned pointer. It must be Send
    /// and 'static; panics propagate on the collecting thread. Delivery has no
    /// time bound and is not guaranteed at process exit. [`collect`] helps drive
    /// progress but does not synchronously wait for callbacks.
    pub fn defer(self, callback: impl FnOnce(Pointer<A>) + Send + 'static) {
        let guard = epoch::pin();
        // SAFETY: this callback runs only after pre-existing readers unpin.
        guard.defer(move || callback(unsafe { self.reclaim() }));
        guard.flush();
    }

    // Caller guarantees all old readers of this node have finished.
    unsafe fn reclaim(mut self) -> Pointer<A> {
        let link = self.link.take().expect("retired node already consumed");
        unsafe {
            let value = self.adapter.get_value(link);
            self.adapter.link_ops().release(link);
            self.adapter.pointer_ops().from_raw(value)
        }
    }
}

impl<A: EpochAdapter> Drop for Retired<A>
where
    A::LinkOps: ConcurrentLinkOps,
    Pointer<A>: Send + 'static,
{
    fn drop(&mut self) {
        if let Some(link) = self.link.take() {
            Self {
                link: Some(link),
                adapter: self.adapter.clone(),
            }
            .defer(drop);
        }
    }
}

/// Helps advance the global epoch collector and flush deferred callbacks.
///
/// This is not a grace-period barrier. Call periodically while awaiting retired
/// nodes, releasing every epoch guard between calls. A stalled pinned thread
/// can indefinitely delay reclamation. Epoch metadata may allocate internally.
pub fn collect() {
    epoch::pin().flush();
}

/// A sharded Treiber stack using caller-provided links and epoch reclamation.
///
/// Requires the default-enabled `intrusive` feature. Push/pop do not allocate
/// wrapper nodes or take a shard lock. Epoch registration/deferred callbacks
/// may allocate; custom adapter operations and callbacks can also have costs.
/// Ordering, empty scans, and gradual close match `ConcurrentShardedStack`.
///
/// Pop returns a [`Retired`] token, **not** immediate ownership of the value.
/// Its link remains claimed until the grace period; this prevents reuse ABA.
///
/// ```
/// use concurrent_sharded_stack::{EpochAdapter, IntrusiveShardedStack, intrusive_collections};
/// use intrusive_collections::{intrusive_adapter, SinglyLinkedListAtomicLink};
/// #[derive(Debug)]
/// struct Entry { link: SinglyLinkedListAtomicLink, value: usize }
/// intrusive_adapter!(EntryAdapter = Box<Entry>: Entry { link => SinglyLinkedListAtomicLink });
/// // SAFETY: the generated adapter is stateless and Box keeps its node alive
/// // at a stable address until the matching pointer conversion.
/// unsafe impl EpochAdapter for EntryAdapter {}
/// let stack = IntrusiveShardedStack::with_concurrency(4, EntryAdapter::new());
/// stack.push(Box::new(Entry { link: SinglyLinkedListAtomicLink::new(), value: 42 })).unwrap();
/// stack.pop().unwrap().defer(|entry| {
///     assert_eq!(entry.value, 42);
///     assert!(!entry.link.is_linked());
/// });
/// ```
pub struct IntrusiveShardedStack<A: EpochAdapter>
where
    A::LinkOps: ConcurrentLinkOps,
    Pointer<A>: Send + 'static,
{
    shards: Box<[CachePadded<Atomic<Link<A>>>]>,
    adapter: A,
}

impl<A: EpochAdapter> IntrusiveShardedStack<A>
where
    A::LinkOps: ConcurrentLinkOps,
    Pointer<A>: Send + 'static,
{
    /// Creates a stack using available parallelism as the shard-count hint.
    pub fn new(adapter: A) -> Self {
        let count = std::thread::available_parallelism()
            .map(|n| n.get().next_power_of_two())
            .unwrap_or(4);
        Self::with_concurrency(count, adapter)
    }
    /// Creates a nonzero power-of-two number of shards, otherwise panics.
    pub fn with_concurrency(shard_count: usize, adapter: A) -> Self {
        assert!(
            shard_count.is_power_of_two(),
            "shard_count must be a nonzero power of two"
        );
        assert!(
            std::mem::align_of::<Link<A>>() >= 2,
            "link alignment must leave a close tag bit"
        );
        Self {
            shards: (0..shard_count)
                .map(|_| CachePadded::new(Atomic::null()))
                .collect(),
            adapter,
        }
    }
    /// Pushes into the local shard. Closed rejection returns the original pointer.
    ///
    /// Panics if the selected link is already claimed (including retirement).
    pub fn push(&self, value: Pointer<A>) -> Result<(), PushError<Pointer<A>>> {
        let guard = &epoch::pin();
        let shard = &self.shards[self.current_shard_index()];
        if shard.load(Ordering::Acquire, guard).tag() == CLOSED_TAG {
            return Err(PushError::Closed(value));
        }
        let raw = self.adapter.pointer_ops().into_raw(value);
        // SAFETY: the erased pointer owns a stable live node; adapter methods do
        // not panic. Failure to acquire leaves the existing owner untouched.
        let link = unsafe { self.adapter.get_link(raw) };
        if !unsafe { self.adapter.link_ops().try_acquire(link) } {
            drop(unsafe { self.adapter.pointer_ops().from_raw(raw) });
            panic!("attempted to insert an object that is already linked or retired");
        }
        let node = Shared::from(link.as_ptr() as *const Link<A>);
        loop {
            let head = shard.load(Ordering::Acquire, guard);
            if head.tag() == CLOSED_TAG {
                // Not published: no readers can have seen this ownership cycle.
                unsafe {
                    self.adapter.link_ops().release(link);
                }
                return Err(PushError::Closed(unsafe {
                    self.adapter.pointer_ops().from_raw(raw)
                }));
            }
            unsafe {
                self.adapter
                    .link_ops()
                    .store_next(link, NonNull::new(head.as_raw() as *mut Link<A>));
            }
            if shard
                .compare_exchange_weak(head, node, Ordering::Release, Ordering::Relaxed, guard)
                .is_ok()
            {
                return Ok(());
            }
            std::hint::spin_loop();
        }
    }
    /// Removes a node, returning a token that delays access until readers finish.
    /// `Empty` is a retryable scan result; `Closed` means closed and drained,
    /// but does not mean all previously retired callbacks have run.
    pub fn pop(&self) -> Result<Retired<A>, PopError> {
        let adapter = self.adapter.clone();
        let guard = &epoch::pin();
        let mut all_closed = true;
        for mask in 0..self.shards.len() {
            let shard = &self.shards[self.current_shard_index() ^ mask];
            loop {
                let head = shard.load(Ordering::Acquire, guard);
                let Some(link) = NonNull::new(head.as_raw() as *mut Link<A>) else {
                    all_closed &= head.tag() == CLOSED_TAG;
                    break;
                };
                // SAFETY: pin protects this acquired link. Next is immutable
                // while published or retired; release/reuse waits for this guard.
                let next = unsafe { adapter.link_ops().load_next(link) };
                let next = next
                    .map_or(Shared::null(), |p| {
                        Shared::from(p.as_ptr() as *const Link<A>)
                    })
                    .with_tag(head.tag());
                if shard
                    .compare_exchange(head, next, Ordering::AcqRel, Ordering::Relaxed, guard)
                    .is_ok()
                {
                    return Ok(Retired {
                        link: Some(link),
                        adapter,
                    });
                }
                std::hint::spin_loop();
            }
        }
        Err(if all_closed {
            PopError::Closed
        } else {
            PopError::Empty
        })
    }
    /// Closes each shard; returns whether this call closed at least one shard.
    /// Existing nodes remain available to pop. Concurrent callers may both win.
    pub fn close(&self) -> bool {
        let guard = &epoch::pin();
        let mut changed = false;
        for shard in &self.shards {
            loop {
                let head = shard.load(Ordering::Acquire, guard);
                if head.tag() == CLOSED_TAG {
                    break;
                }
                if shard
                    .compare_exchange_weak(
                        head,
                        head.with_tag(CLOSED_TAG),
                        Ordering::AcqRel,
                        Ordering::Relaxed,
                        guard,
                    )
                    .is_ok()
                {
                    changed = true;
                    break;
                }
                std::hint::spin_loop();
            }
        }
        changed
    }
    /// Checks whether every shard is closed.
    pub fn is_closed(&self) -> bool {
        let guard = &epoch::pin();
        self.shards
            .iter()
            .all(|s| s.load(Ordering::Acquire, guard).tag() == CLOSED_TAG)
    }
    /// Returns the fixed number of shards.
    pub fn shard_count(&self) -> usize {
        self.shards.len()
    }
    fn current_shard_index(&self) -> usize {
        current_thread_id() & (self.shards.len() - 1)
    }
}

impl<A: EpochAdapter + Default> Default for IntrusiveShardedStack<A>
where
    A::LinkOps: ConcurrentLinkOps,
    Pointer<A>: Send + 'static,
{
    fn default() -> Self {
        Self::new(A::default())
    }
}

impl<A: EpochAdapter> Drop for IntrusiveShardedStack<A>
where
    A::LinkOps: ConcurrentLinkOps,
    Pointer<A>: Send + 'static,
{
    fn drop(&mut self) {
        let drain = || {
            // SAFETY: exclusive stack access means no stack operation can still
            // read its reachable nodes. Retired nodes are separately owned.
            let guard = unsafe { epoch::unprotected() };
            for shard in &self.shards {
                loop {
                    let head = shard.load(Ordering::Relaxed, guard);
                    let Some(link) = NonNull::new(head.as_raw() as *mut Link<A>) else {
                        break;
                    };
                    unsafe {
                        let next = self.adapter.link_ops().load_next(link);
                        shard.store(
                            next.map_or(Shared::null(), |p| {
                                Shared::from(p.as_ptr() as *const Link<A>)
                            }),
                            Ordering::Relaxed,
                        );
                        drop(
                            Retired {
                                link: Some(link),
                                adapter: self.adapter.clone(),
                            }
                            .reclaim(),
                        );
                    }
                }
            }
        };
        let cleanup = scopeguard::guard((), |_| drain());
        drain();
        scopeguard::ScopeGuard::into_inner(cleanup);
    }
}
